### ISSUE TITLE
Quest:  The Last Line of Defense.

### ISSUE THREAD

**Issue by KummieShot** [WoWPortal/Paradox-Emu#12]
**Describe the bug**
Frostbrood Destroyers cannot be killed.

**To Reproduce**
Start the quest, hop on a canon, shoot the Dragons, and they instantly heal back to full.

**Expected behavior**
They die in a few shots.
**Screenshots**

**Additional context**

**Comment by WoWPortal** [comment]
Issue is now resolved fix will be applied at next reboot

**Comment by WoWPortal** [comment]
Issue is now fixed

**Comment by Elounia** [comment]
Confirmed the Wyrms are now able to be killed, but now neither they or the spiders count towards the quest progress. It simply stays at 0/3 and 0/100.
