### ISSUE TITLE
Quest: The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by KummieShot** [WoWPortal/Paradox-Emu#6]
**Describe the bug**
A clear and concise description of what the bug is. Provide links to Quests/Spells from https://wotlk.cavernoftime.com/

**To Reproduce**
1.  Start the exorcism

**Expected behavior**
Small waves of enemies spawn, 4-6 at a time, with brief pauses between.

What actually happens, is hundreds spawn at a time, making it impossible to complete due to the AI being killed.

**Screenshots**

**Additional context**

**Comment by WoWPortal** [comment]
Thank you for the report will be fixing shortly

**Comment by WoWPortal** [comment]
Issue is now fixed
