### ISSUE TITLE
Quest: Plans of Zangarmarsh

### ISSUE THREAD

**Issue by KummieShot** [WoWPortal/Paradox-Emu#7]
**Describe the bug**
Own the 10 strange plants, can't hand in the quest.  Greyed out like I don't own them

**To Reproduce**

1.  Farm the 10 plants, go to hand in, nothing happens.

**Expected behavior**
Quest completes as normal
**Screenshots**
https://i.gyazo.com/c1ab3ed876da6c9264d055e9fef76856.jpg
**Additional context**

**Comment by pottedfrog** [comment]
You can only hand in plant parts until you are honoured with Cenarion - check your reputation in case you are already honoured.

If you are honoured, the bug is the quest being available at all.

**Comment by KummieShot** [comment]
Good thing I'm revered and still can't hand it in.  Leave the replies to GM's.

**Comment by WoWPortal** [comment]
applying a fix now
